#!/bin/bash

# SPDX-FileCopyrightText: 2020-2026 Tigerblue77 and the Dell OMSA Docker image contributors
# SPDX-License-Identifier: AGPL-3.0-only

# The environment every test case runs in, and the few helpers that talk to the
# code under test.
#
# What is being tested here is a container entrypoint : a one-shot provisioning
# script that ends in "exec /sbin/init". It is not a library, so nothing can be
# sourced and called function by function -- it is run as a process, from start
# to finish, and what it did is read back afterwards from the filesystem it
# wrote and from what the mocked commands recorded.
#
# That script writes to absolute paths belonging to the machine it runs on :
# /etc/passwd, /etc/rc.local, /opt/dell/srvadmin/etc/omarolemap, two systemd
# units under /usr/lib/systemd/system, and it hands the machine over to
# /sbin/init. A mock first in the PATH cannot intercept any of them, an absolute
# path being resolved without ever consulting the PATH. Running the script as it
# ships would therefore provision the machine running the suite -- create a user
# on it, set that user's password, and replace its /etc/rc.local.
#
# The seam is therefore a sandbox ROOT rather than a mocked command : the script
# is copied into $TEST_ROOT with each of those absolute paths rewritten to the
# same path underneath it, so that "> /etc/rc.local" becomes
# "> $TEST_ROOT/etc/rc.local" and writes inside a directory this run created and
# deletes. The commands it calls by name (adduser, chpasswd, systemctl, chmod,
# rm) are mocked the usual way, first in the PATH.

# Every absolute path configure_and_run_Dell_OMSA.sh names, and what the sandbox
# does with each of them. This map is the whole safety property of the suite, so
# it is written out by hand rather than generated by a blind
# "sed s|/|$TEST_ROOT/|g" : a substitution that rewrites whatever looks like a
# path also rewrites the ones that must not be touched (the shebang, and the
# command rc.local is made to run on the real machine), and, being generated, it
# would silently absorb a path added to the entrypoint later instead of making
# somebody decide what to do with it.
#
# Deciding is the point. test_every_absolute_path_the_entrypoint_names_is_declared_in_the_sandbox_map
# reads the real script, extracts every absolute path in it and fails when one is
# missing from this map, so an edit that adds a write to a new absolute path
# cannot reach the machine running the suite : it turns the suite red first, and
# whoever added it says here whether that path is sandboxed or deliberately left
# alone.
#
#   sandbox   the entrypoint opens, writes, tests or executes it, so the copy is
#             pointed at $TEST_ROOT/<the same path>
#   verbatim  the entrypoint never touches it -- it is text it writes into a
#             file, or its own shebang -- so rewriting it would change what the
#             script means rather than where it writes
declare -a ENTRYPOINT_ABSOLUTE_PATHS=(
  # Read to decide whether the user already exists
  "/etc/passwd=sandbox"
  # Written, then made executable
  "/etc/rc.local=sandbox"
  # Written : the OMSA role map that grants the user its rights
  "/opt/dell/srvadmin/etc/omarolemap=sandbox"
  # Tested with -e, then removed
  "/usr/lib/systemd/system/getty@.service=sandbox"
  "/usr/lib/systemd/system/autovt@.service=sandbox"
  # Executed, as the last thing the entrypoint does
  "/sbin/init=sandbox"
  # Written INTO rc.local as the command the real machine will run at boot, and
  # never run by the entrypoint itself. Rewritten, it would make the sandbox
  # assert against a path that only exists because the test rewrote it, and hide
  # the one thing rc.local is checked for : that it calls OMSA's own service
  # script at the place OMSA installs it
  "/opt/dell/srvadmin/sbin/srvadmin-services.sh=verbatim"
  # Two shebangs : the entrypoint's own, and the one it writes at the top of
  # rc.local. The copy is run as "sh <file>", so its shebang is not even read ;
  # rewriting either would only produce a file naming an interpreter that does
  # not exist
  "/bin/sh=verbatim"
)

# The entrypoint, as the repository ships it
function entrypoint_path() {
  printf '%s' "$REPO_ROOT/configure_and_run_Dell_OMSA.sh"
}

# Every absolute path a file names, one per line, deduplicated.
#
# Read over every line, comments included. Stripping comments first would be the
# obvious thing and is the wrong thing : the entrypoint carries
# `echo "#!/bin/sh" > /etc/rc.local`, and a comment-stripping pass cuts that line
# at the "#" inside the string and loses the "/etc/rc.local" after it -- which is
# precisely one of the paths that must not escape. Reading everything can only
# ask for a map entry that turns out to be unnecessary ; reading less can miss
# the one that matters
# Usage : absolute_paths_named_in FILE
function absolute_paths_named_in() {
  grep -oE '/[A-Za-z0-9_][A-Za-z0-9._@+-]*(/[A-Za-z0-9._@+-]+)*' "$1" | sort -u
}

# The paths of the map, filtered by disposition
# Usage : mapped_absolute_paths [sandbox|verbatim]
function mapped_absolute_paths() {
  local -r WANTED_DISPOSITION="${1:-}"

  local ENTRY
  for ENTRY in "${ENTRYPOINT_ABSOLUTE_PATHS[@]}"; do
    [ -z "$WANTED_DISPOSITION" ] || [ "${ENTRY##*=}" == "$WANTED_DISPOSITION" ] || continue
    printf '%s\n' "${ENTRY%%=*}"
  done
}

# Longest first, so that a path which is a prefix of another one cannot consume
# it halfway through the rewrite. None of the entries is a prefix of another
# today ; ordering the substitution is what keeps that from being a condition
# the next entry has to remember
function sandboxed_absolute_paths_longest_first() {
  mapped_absolute_paths sandbox |
    awk '{ print length, $0 }' | sort -rn | cut -d' ' -f2-
}

# Where a path of the managed machine lives inside the sandbox
# Usage : sandbox_path /etc/rc.local
function sandbox_path() {
  printf '%s' "$TEST_ROOT$1"
}

# The content of a sandboxed file, empty when it does not exist (its absence
# being an outcome a test case reads as often as its content)
# Usage : sandbox_file_content /etc/rc.local
function sandbox_file_content() {
  local -r FILE="$(sandbox_path "$1")"

  [ -f "$FILE" ] || return 0
  cat "$FILE"
}

# Usage : if sandbox_file_exists /etc/rc.local; then ...
function sandbox_file_exists() {
  [ -e "$(sandbox_path "$1")" ]
}

# Copy the entrypoint into the sandbox, with every "sandbox" path of the map
# rewritten to the same path underneath $TEST_ROOT.
#
# The substitution is done by bash rather than by sed : the patterns are file
# paths, where a "." would be a regex metacharacter in sed and would match a
# character the map never named. Quoted, "${CONTENT//"$PATH"/...}" is a literal
# replacement, and the quoting of the replacement is what keeps bash 5.2's
# patsub_replacement from reading an "&" in $TEST_ROOT as "whatever matched"
function write_sandboxed_entrypoint() {
  local CONTENT
  CONTENT=$(cat "$(entrypoint_path)")

  local ABSOLUTE_PATH
  while IFS= read -r ABSOLUTE_PATH; do
    [ -n "$ABSOLUTE_PATH" ] || continue
    CONTENT="${CONTENT//"$ABSOLUTE_PATH"/"$TEST_ROOT$ABSOLUTE_PATH"}"
  done < <(sandboxed_absolute_paths_longest_first)

  printf '%s\n' "$CONTENT" > "$SANDBOXED_ENTRYPOINT"
  command -p chmod +x "$SANDBOXED_ENTRYPOINT"
}

# The absolute paths of a sandboxed script that would still reach the machine
# running the suite. One line per offender, empty when the copy is contained.
#
# Written as an allow list rather than as a deny list, which is the difference
# between a guard and a reminder. A deny list -- "flag the paths the map calls
# sandbox and that were not rewritten" -- knows nothing about a path nobody
# declared, so the one edit this whole seam exists to catch would walk straight
# past it and be caught only by the meta case, in one test case out of fifty
# while the other forty-nine ran the script anyway.
#
# So : a path is acceptable when it lives under $TEST_ROOT, and otherwise only
# when the map declares it verbatim, deliberately. Everything else is reported,
# whether it is a declared path the substitution missed or a path added to the
# entrypoint since anybody last read this file.
#
# This is the property test_the_sandboxed_entrypoint_leaves_no_absolute_path_pointing_outside_the_sandbox
# asserts, checked again by run_entrypoint() immediately before it runs anything.
# Belt and braces on purpose : the assertion protects the design, this protects
# the machine, and only one of the two runs before the script does
# Usage : absolute_paths_escaping_the_sandbox FILE
function absolute_paths_escaping_the_sandbox() {
  local -r PATHS_ALLOWED_VERBATIM="$(mapped_absolute_paths verbatim)"

  local ABSOLUTE_PATH
  while IFS= read -r ABSOLUTE_PATH; do
    [ -n "$ABSOLUTE_PATH" ] || continue

    # Already inside the sandbox, either rewritten or written there to begin with
    case "$ABSOLUTE_PATH" in
      "$TEST_ROOT"/*) continue ;;
    esac

    printf '%s\n' "$PATHS_ALLOWED_VERBATIM" | grep -qxF "$ABSOLUTE_PATH" && continue

    printf '%s\n' "$ABSOLUTE_PATH"
  done < <(absolute_paths_named_in "$1")
}

# The /etc/passwd the sandbox starts from : root and the handful of system
# accounts any distribution carries, and no account named after what a test case
# is about to ask for. A test case that wants one there calls
# given_the_sandbox_already_has_the_user
readonly DEFAULT_SANDBOX_PASSWD_CONTENT='root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
nobody:x:65534:65534:Kernel Overflow User:/:/sbin/nologin'

# Prepare the environment a test case starts from : a throwaway sandbox root, the
# entrypoint copied into it with its absolute paths rewritten, the mocks first in
# the PATH, and the variables the Docker image sets.
#
# Called by the runner inside each test case's own subshell, so everything it
# changes -- PATH, the exported mock variables, the working directory -- is that
# case's alone
function setup_test_context() {
  TEST_ROOT="$TEST_TEMPORARY_DIRECTORY/root"
  export TEST_ROOT

  # "command -p" throughout : the mocks are about to be first in the PATH, and
  # two of the commands the entrypoint uses (rm, chmod) are commands this
  # function needs as well
  command -p rm -rf "$TEST_ROOT"
  command -p mkdir -p "$TEST_ROOT"

  # The directories the rewritten paths need. Derived from the map rather than
  # listed a second time : a directory list that has to be kept in step with the
  # map is a second copy of it, and the copy is what goes stale
  local ABSOLUTE_PATH
  while IFS= read -r ABSOLUTE_PATH; do
    [ -n "$ABSOLUTE_PATH" ] || continue
    command -p mkdir -p "$TEST_ROOT$(dirname "$ABSOLUTE_PATH")"
  done < <(mapped_absolute_paths sandbox)

  command -p mkdir -p "$TEST_ROOT/mock_calls" "$TEST_ROOT/run"

  # The managed machine as the image finds it : a passwd file, the two systemd
  # units AlmaLinux ships, and OMSA's own role map, already installed by
  # srvadmin-all. rc.local is deliberately absent -- the entrypoint creates it
  printf '%s\n' "$DEFAULT_SANDBOX_PASSWD_CONTENT" > "$(sandbox_path /etc/passwd)"
  given_the_systemd_units_exist
  printf '%s\n' '# All rights reserved. Dell OpenManage Server Administrator role map.' \
    > "$(sandbox_path /opt/dell/srvadmin/etc/omarolemap)"

  SANDBOXED_ENTRYPOINT="$TEST_ROOT/configure_and_run_Dell_OMSA.sh"
  export SANDBOXED_ENTRYPOINT
  write_sandboxed_entrypoint

  # /sbin/init is executed rather than called by name, so its mock is installed
  # at the sandboxed path the copy now names instead of being found in the PATH
  command -p cp "$TESTS_DIRECTORY/mocks/init" "$(sandbox_path /sbin/init)"
  command -p chmod +x "$(sandbox_path /sbin/init)"

  PATH="$TESTS_DIRECTORY/mocks:$PATH"
  export PATH

  # One call log per mocked command, all under the sandbox so that they go with
  # it when the next test case rebuilds it
  export MOCK_CALL_LOG_DIRECTORY="$TEST_ROOT/mock_calls"
  export MOCK_ADDUSER_CALL_LOG="$MOCK_CALL_LOG_DIRECTORY/adduser.log"
  export MOCK_USERADD_CALL_LOG="$MOCK_CALL_LOG_DIRECTORY/useradd.log"
  export MOCK_CHPASSWD_CALL_LOG="$MOCK_CALL_LOG_DIRECTORY/chpasswd.log"
  export MOCK_SYSTEMCTL_CALL_LOG="$MOCK_CALL_LOG_DIRECTORY/systemctl.log"
  export MOCK_CHMOD_CALL_LOG="$MOCK_CALL_LOG_DIRECTORY/chmod.log"
  export MOCK_RM_CALL_LOG="$MOCK_CALL_LOG_DIRECTORY/rm.log"
  export MOCK_GETENT_CALL_LOG="$MOCK_CALL_LOG_DIRECTORY/getent.log"
  export MOCK_INIT_CALL_LOG="$MOCK_CALL_LOG_DIRECTORY/init.log"
  # What chpasswd is handed on its standard input, which is where the password
  # travels and the only place a test can read it back from
  export MOCK_CHPASSWD_STDIN_LOG="$MOCK_CALL_LOG_DIRECTORY/chpasswd.stdin"

  local CALL_LOG
  for CALL_LOG in "$MOCK_ADDUSER_CALL_LOG" "$MOCK_USERADD_CALL_LOG" "$MOCK_CHPASSWD_CALL_LOG" \
    "$MOCK_SYSTEMCTL_CALL_LOG" "$MOCK_CHMOD_CALL_LOG" "$MOCK_RM_CALL_LOG" \
    "$MOCK_GETENT_CALL_LOG" "$MOCK_INIT_CALL_LOG" "$MOCK_CHPASSWD_STDIN_LOG"; do
    : > "$CALL_LOG"
  done

  # The user database the account mocks read and write is the sandbox's own,
  # never the machine's
  export MOCK_ADDUSER_PASSWD_FILE="$(sandbox_path /etc/passwd)"
  export MOCK_USERADD_PASSWD_FILE="$MOCK_ADDUSER_PASSWD_FILE"
  export MOCK_GETENT_PASSWD_FILE="$MOCK_ADDUSER_PASSWD_FILE"

  # Dockerfile defaults. The image sets exactly two environment variables of its
  # own, and declares no value for the two the entrypoint refuses to start
  # without -- so those two start unset here, which is what "docker run" without
  # them gives the container
  export SYSTEMCTL_SKIP_REDIRECT=1
  unset OMSA_username OMSA_password

  # What the last run left in the test case's own variables
  ENTRYPOINT_STDOUT=""
  ENTRYPOINT_STDERR=""
  ENTRYPOINT_OUTPUT=""
  ENTRYPOINT_EXIT_CODE=0
}

# The two units the entrypoint removes, present the way the base image ships
# them. The default state of the sandbox ; a test case that wants them gone
# calls given_the_systemd_units_are_absent
function given_the_systemd_units_exist() {
  local UNIT
  for UNIT in /usr/lib/systemd/system/getty@.service /usr/lib/systemd/system/autovt@.service; do
    printf '%s\n' '[Unit]' 'Description=Getty on %I' > "$(sandbox_path "$UNIT")"
  done
}

function given_the_systemd_units_are_absent() {
  command -p rm -f "$(sandbox_path /usr/lib/systemd/system/getty@.service)" \
    "$(sandbox_path /usr/lib/systemd/system/autovt@.service)"
}

# Put an account in the sandbox's /etc/passwd, so that the entrypoint finds the
# user already there
# Usage : given_the_sandbox_already_has_the_user "omsauser" [shell]
function given_the_sandbox_already_has_the_user() {
  local -r USERNAME="$1"
  local -r LOGIN_SHELL="${2:-/bin/bash}"

  printf '%s:x:1000:1000::/home/%s:%s\n' "$USERNAME" "$USERNAME" "$LOGIN_SHELL" \
    >> "$(sandbox_path /etc/passwd)"
}

# The credentials the container is started with
# Usage : given_the_credentials "omsauser" "hunter2"
function given_the_credentials() {
  export OMSA_username="$1"
  export OMSA_password="$2"
}

# Where a mocked command records what it was called with
# Usage : call_log_of systemctl
function call_log_of() {
  printf '%s' "$MOCK_CALL_LOG_DIRECTORY/$1.log"
}

# Every invocation a mocked command recorded so far, one per line : the
# command's own name, then its arguments as it was given them. The name is part
# of the line so that a command called with no argument at all -- chpasswd, which
# takes everything on its standard input -- still records something a pattern can
# match, rather than an empty line indistinguishable from no call
# Usage : recorded_calls adduser
function recorded_calls() {
  cat "$(call_log_of "$1")"
}

# Number of recorded invocations of a command matching an extended regular
# expression. The mirror of the sibling repository's
# count_ipmitool_calls_matching, with the command to look at as its first
# argument, there being more than one of them here
# Usage : count_calls_matching systemctl "enable rc-local"
function count_calls_matching() {
  grep -cE -- "$2" "$(call_log_of "$1")" || true
}

# Forget the invocations recorded so far, for a test case that runs the
# entrypoint twice and is about the second run
# Usage : forget_recorded_calls adduser chpasswd
function forget_recorded_calls() {
  local COMMAND
  for COMMAND in "$@"; do
    : > "$(call_log_of "$COMMAND")"
  done
}

# What chpasswd was handed on its standard input across the whole run : one
# "user:password" line per invocation, which is where the password travels
function recorded_chpasswd_input() {
  cat "$MOCK_CHPASSWD_STDIN_LOG"
}

# Run the sandboxed entrypoint the way the image runs it, and record what it did.
#
# Its two output streams are kept apart rather than merged, so that a test case
# can hold a rewrite to sending its refusals to stderr without being unable to
# read them today ; $ENTRYPOINT_OUTPUT is the two of them together, which is
# what "docker logs" shows and what a message assertion should normally use.
#
# It always returns 0, whatever the entrypoint did. The entrypoint's own status
# is in $ENTRYPOINT_EXIT_CODE, and a test case reads it from there : returning it
# would make a case whose last statement is this call be reported as a test that
# crashed, every time it exercised a refusal.
#
# Usage : run_entrypoint; assert_equals 1 "$ENTRYPOINT_EXIT_CODE"
function run_entrypoint() {
  ENTRYPOINT_STDOUT=""
  ENTRYPOINT_STDERR=""
  ENTRYPOINT_OUTPUT=""
  ENTRYPOINT_EXIT_CODE=0

  # Nothing is run until the copy is known to be contained. A rewrite that
  # missed a path would otherwise provision the machine running the suite, and
  # it would do it before any assertion had a chance to say so
  local ESCAPING_PATHS
  ESCAPING_PATHS=$(absolute_paths_escaping_the_sandbox "$SANDBOXED_ENTRYPOINT")
  if [ -n "$ESCAPING_PATHS" ]; then
    fail "the sandboxed entrypoint still names paths of the machine running the suite, so it was not run" \
      "$(printf '%s' "$ESCAPING_PATHS" | tr '\n' ' ')"
    return 0
  fi

  local -r STANDARD_OUTPUT_FILE="$TEST_ROOT/run/stdout"
  local -r STANDARD_ERROR_FILE="$TEST_ROOT/run/stderr"

  sh "$SANDBOXED_ENTRYPOINT" > "$STANDARD_OUTPUT_FILE" 2> "$STANDARD_ERROR_FILE" ||
    ENTRYPOINT_EXIT_CODE=$?

  ENTRYPOINT_STDOUT=$(cat "$STANDARD_OUTPUT_FILE")
  ENTRYPOINT_STDERR=$(cat "$STANDARD_ERROR_FILE")
  ENTRYPOINT_OUTPUT=$(cat "$STANDARD_OUTPUT_FILE" "$STANDARD_ERROR_FILE")

  return 0
}

# Whether the entrypoint reached its handover to /sbin/init, which is the last
# thing it does and therefore the only evidence that everything before it ran
function the_entrypoint_reached_init() {
  [ -s "$MOCK_INIT_CALL_LOG" ]
}
